image: archlinux
packages:
  - man-db
  - man-pages
  - neovim
  - ripgrep
  - fzf
  - just
  - python
  - lua
sources:
  - https://git.sr.ht/~adigitoleo/haunt.nvim
tasks:
  - test: |
      cd haunt.nvim
      just test
